# Introduction
## Basic math functions

* `+` - Addition 
* `-` - Subtraction 
* `*` -  Multiplication
* `/` - Division
* `**` - Exponential 

## Same operators on string

* `+` - concat
* `*` - replication

In [1]:
print(1+1)
print(1-1)
print(1*3)
print(1/3)
print(4**2)

2
0
3
0.3333333333333333
16


In [2]:
print("Hello "+"Sam")
print("Hello "*3)

Hello Sam
Hello Hello Hello 


## Transformation functions

* int()

* float()

* string()

In [3]:
myName = input()

In [4]:
len(myName)

4

In [5]:
float(10)

10.0

In [6]:
int(1.0)

1

In [7]:
str(10)

'10'

## String operation and other basics

### Function used

* split()

* .format()

* lower()

* len()

In [8]:
s = "Hi Hari"
# Split default is ` `
s.split()

['Hi', 'Hari']

In [9]:
e = 'harikrishnad1997@gmail.com'

In [10]:
e.split('@')

['harikrishnad1997', 'gmail.com']

In [11]:
s.lower()

'hi hari'

In [12]:
len(s)

7

In [13]:
print("{} How are you?".format(s))

Hi Hari How are you?


## Flow control basics

### Booleans

* `==` - equal to

* `!=` - not equal to

* `>` - less than

* `<` - greater than

In [14]:
42 == 42

True

In [15]:
42 >= 42

True

In [16]:
myAge = 25
myAge >= 29

False

### Boolean operators

* `and`

* `or`

In [17]:
True or False

True

In [18]:
False and True

False

In [19]:
True or False and False

True

### Flow control

* `if` , `else` , `elif`

* `while`, `break`, `continue`, `pass`

* `for` loop

In [20]:
number = -102

if number > 0:
    print("Positive number")

elif number == 0:
    print('Zero')
else:
    print('Negative number')

Negative number


In [21]:
# program to display numbers from 1 to 5

# initialize the variable
i = 1
n = 5

# while loop from i = 1 to 5
while i <= n:
    print(i)
    i = i + 1

1
2
3
4
5


In [22]:
# program to find first 5 multiples of 6

i = 1

while i <= 10:
    print('6 * ',(i), '=',6 * i)

    if i >= 5:
        break
    
    i = i + 1

6 *  1 = 6
6 *  2 = 12
6 *  3 = 18
6 *  4 = 24
6 *  5 = 30


In [23]:
for i in range(5):
    if i == 3:
        continue
    print(i)

0
1
2
4


In [24]:
n = 10

# use pass inside if statement
if n > 10:
    pass

print('Hello')

Hello


In [25]:
# use of range() to define a range of values
values = range(4)

# iterate from i = 0 to i = 3
for i in values:
    print(i)

0
1
2
3


### Numpy exercises

In [1]:
import numpy as np

In [4]:
# Array of zeros
np.zeros(10)
np.zeros(9).reshape(3,3)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [5]:
# Array of ones
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [6]:
# Array of 5s
np.ones(5)*5

array([5., 5., 5., 5., 5.])

In [11]:
# array of intergers from 10 to 50
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [12]:
np.arange(10,50,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

In [13]:
# 3 X 3 matrix
np.ones(9).reshape(3,3)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [14]:
# Identity matrix
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [15]:
np.random.rand()

0.6366794468923689

In [18]:
np.random.rand(9).reshape(3,3)

array([[0.34046962, 0.18920337, 0.86823913],
       [0.79672261, 0.69894992, 0.79819294],
       [0.31355382, 0.83396241, 0.55447731]])

In [26]:
np.arange(0.01,1.01,0.01).reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [28]:
# Line spaced
np.linspace(0,1,20) 

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

### Numpy indexing and selection

In [29]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [30]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [31]:
mat[3,4]

20

In [32]:
mat[:3,1:2]

array([[ 2],
       [ 7],
       [12]])

#### Matrix functions

In [33]:
mat.sum()

325

In [34]:
mat.std()

7.211102550927978

In [35]:
mat.sum(axis = 1)

array([ 15,  40,  65,  90, 115])

In [36]:
mat.sum(axis =0)

array([55, 60, 65, 70, 75])

### Pandas

#### Series